---
output: 
  html_document:
    code_folding: show
title: Appalachicola exploration
---

Import the data and combine tidal vectors at hourly time step. 

```{r setup}
knitr::opts_chunk$set(warning = F, message = F, out.width = '100%')

box::use(
  dplyr[...], 
  tidyr[...],
  here[...], 
  janitor[...], 
  lubridate[...]
)

tz <- 'America/Jamaica'

# import data, combine at hourly timestep
cp <- read.csv(here('data-raw/apa_cp_02.csv')) %>% 
  mutate(
    datetimestamp = ymd_hms(datetimestamp, tz = tz), 
    loc = 'cp'
  ) %>% 
  filter(minute(datetimestamp) == 0) %>% 
  select(loc, datetimestamp, tide = depth)
db <- read.csv(here('data-raw/apa_db_data_02.csv')) %>% 
  mutate(
    datetimestamp = ymd_hms(datetimestamp, tz = tz), 
    loc = 'db'
  ) %>% 
  filter(minute(datetimestamp) == 0) %>% 
  select(loc, datetimestamp, tide = depth)
noaa <- read.csv(here('data-raw/noaa_tide_2002.csv')) %>% 
  clean_names() %>% 
  unite('datetimestamp', date, time_lst, sep = ' ') %>% 
  mutate(
    datetimestamp = ymd_hm(datetimestamp, tz = tz), 
    tide = predicted_ft * 0.3048, 
    loc = 'noaa'
  ) %>% 
  select(loc, datetimestamp, tide)
                    
alldat <- bind_rows(cp, db, noaa)  %>% 
  spread(loc, tide) %>% 
  mutate_if(is.numeric, as.ts)
```

Pairwise scatterplots of tidal vectors.

```{r, fig.height = 3, fig.width = 7}
par(mfrow = c(1, 3), mar = c(4, 4, 0.5, 0.5))
plot(db ~ cp, alldat)
abline(reg = lm(db ~ cp, alldat), col = 'blue')
plot(noaa ~ cp, alldat)
abline(reg = lm(noaa ~ cp, alldat), col = 'blue')
plot(noaa ~ db, alldat)
abline(reg = lm(noaa ~ db, alldat), col = 'blue')
```

Use `ccf`to check lagged correlations, each lag corresponds to one hour.  

# {.tabset .tabset-pills}

## Dry bar and Cat Point

```{r,  fig.height = 5, fig.width = 7}
subs <- 1:90
par(mfrow = c(3, 1), mar = c(4, 4, 0.5, 0.5))
plot(db ~ datetimestamp, alldat[subs, ], type = 'l')
plot(cp ~ datetimestamp, alldat[subs, ], type = 'l')
ccf(alldat$db, alldat$cp, na.action = na.pass)
ccf(alldat$db, alldat$cp, na.action = na.pass, plot = F)
```

## NOAA and Cat Point

```{r,  fig.height = 5, fig.width = 7}
subs <- 1:90
par(mfrow = c(3, 1), mar = c(4, 4, 0.5, 0.5))
plot(noaa ~ datetimestamp, alldat[subs, ], type = 'l')
plot(cp ~ datetimestamp, alldat[subs, ], type = 'l')
ccf(alldat$noaa, alldat$cp, na.action = na.pass)
ccf(alldat$noaa, alldat$cp, na.action = na.pass, plot = F)
```

## NOAA and Dry Bar

```{r,  fig.height = 5, fig.width = 7}
subs <- 1:90
par(mfrow = c(3, 1), mar = c(4, 4, 0.5, 0.5))
plot(noaa ~ datetimestamp, alldat[subs, ], type = 'l')
plot(db ~ datetimestamp, alldat[subs, ], type = 'l')
ccf(alldat$noaa, alldat$db, na.action = na.pass)
ccf(alldat$noaa, alldat$db, na.action = na.pass, plot = F)
```
